# Copy from https://github.com/marketplace/actions/vue-to-github-pages

name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v4
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'RainBWP'
        reponame: 'UI-RestaurantApplication'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
